swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - Accounts
      summary: Get user accounts
      description: Retrieve the list of bank accounts for the user
      produces:
        - application/json
      responses:
        '200':
          description: List of accounts successfully retrieved
          schema:
            type: array
            items:
              $ref: '#/definitions/Account'
        '404':
          description: No accounts found for the user
        '500':
          description: Internal Server Error
  /accounts/{accountId}/transactions:
    get:
      tags:
        - Transaction Module
      summary: Retrieve transactions by account
      description: API to get a list of transactions for a specific account.
      security:
        - Bearer: []
      parameters:
        - name: accountId
          in: path
          description: ID of the account to retrieve transactions for
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Successfully retrieved account transactions
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        '401':
          description: Unauthorized
        '404':
          description: Account not found
        '500':
          description: Internal Server Error
  /transactions/{transactionId}:
    get:
      tags:
        - Transaction Module
      summary: Retrieve a single transaction
      description: API to retrieve details of a specific transaction.
      security:
        - Bearer: []
      parameters:
        - name: transactionId
          in: path
          description: ID of the transaction to retrieve
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: Transaction retrieved successfully
          schema:
            $ref: '#/definitions/Transaction'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - action not authorized
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    patch:
      tags:
        - Transaction Module
      summary: Update transaction information
      description: API to update details of a transaction.
      security:
        - Bearer: []
      parameters:
        - name: transactionId
          in: path
          description: ID of the transaction to update
          required: true
          type: string
        - in: body
          name: body
          description: Update payload for the transaction
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - action not authorized
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  Account:
    type: object
    properties:
      accountId:
        type: string
        description: Unique identifier of the account
      accountName:
        type: string
        description: Name of the bank account
      balance:
        type: number
        description: Available balance in the account
      accountType:
        type: string
        description: Type of the account (e.g., checking, savings)
      balanceStatus:
        type: string
        description: Status or label for the balance (e.g., "Available balance")
  Transaction:
    type: object
    properties:
      transactionId:
        type: string
        description: Unique identifier of the transaction
      date:
        type: string
        format: date
        description: Date of the transaction
      description:
        type: string
        description: Description of the transaction
      amount:
        type: number
        description: Amount of the transaction
      balance:
        type: number
        description: Balance after the transaction
      transactionType:
        type: string
        description: Type of transaction (e.g., Electronic, Check, etc.)
      category:
        type: string
        description: Category of the transaction (e.g., Food, Transport, etc.)
      note:
        type: string
        description: Optional note attached to the transaction
  TransactionUpdate:
    type: object
    properties:
      category:
        type: string
        description: New category for the transaction
      note:
        type: string
        description: Optional note for the transaction